openapi: 3.0.0
info:
  title: Stream Telecom Analytics API
  description: API для анализа и управления рекламными кампаниями
  version: 1.0.0
servers:
  - url: /api/v1
    description: API версии 1
paths:
  /activity:
    get:
      summary: Получение активности кампании
      description: Возвращает метрики активности для указанной кампании за определенный период времени
      parameters:
        - name: campaign_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: ID кампании
        - name: count_hours
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: Количество часов для анализа
      responses:
        "200":
          description: Успешный ответ с метриками активности
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivityMetrics"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /campaigns:
    get:
      summary: Получение списка всех кампаний
      description: Возвращает постраничный список всех кампаний
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: Номер страницы
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Количество элементов на странице
      responses:
        "200":
          description: Успешный ответ со списком кампаний
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  page:
                    type: integer
                  per_page:
                    type: integer
                  campaigns:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int64
                        name:
                          type: string
                        created_at:
                          type: string
                          format: date-time

  /heat-map:
    get:
      summary: Получение тепловой карты активности по регионам
      description: Возвращает данные для построения тепловой карты активности пользователей по регионам
      parameters:
        - name: start_date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Начальная дата в формате YYYY-MM-DD
        - name: end_date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Конечная дата в формате YYYY-MM-DD
      responses:
        "200":
          description: Успешный ответ с данными тепловой карты
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegionHeatMap"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalError"

  /client-hot-point:
    get:
      summary: Получение точек активности клиентов
      description: Возвращает данные о количестве кликов по регионам за период
      parameters:
        - name: start_date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Начальная дата в формате YYYY-MM-DD
        - name: end_date
          in: query
          required: false
          schema:
            type: string
            format: date
          description: Конечная дата в формате YYYY-MM-DD
      responses:
        "200":
          description: Успешный ответ с данными о кликах
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegionClickStats"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalError"

  /client-reaction-speed:
    get:
      summary: Получение времени реакции клиентов
      description: Возвращает метрики времени реакции клиентов для указанной кампании
      parameters:
        - name: campaign_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: ID кампании
      responses:
        "200":
          description: Успешный ответ с метриками времени реакции
          content:
            application/json:
              schema:
                type: object
                properties:
                  average_reaction_time:
                    type: number
                    format: float
                  min_reaction_time:
                    type: number
                    format: float
                  max_reaction_time:
                    type: number
                    format: float
        "400":
          description: Неверные параметры запроса
        "404":
          description: Кампания не найдена

  /click-dynamic/{id}:
    get:
      summary: Получение динамики кликов
      description: Возвращает статистику кликов по дням и месяцам для указанной кампании
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID кампании
      responses:
        "200":
          description: Успешный ответ со статистикой кликов
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CampaignStats"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /create-campaign-dynamic:
    get:
      summary: Получение динамики создания кампаний
      description: Возвращает статистику создания кампаний за указанный период
      parameters:
        - name: interval_type
          in: query
          required: true
          schema:
            type: string
            enum: [day, month]
          description: Тип интервала для группировки (день или месяц)
        - name: start_time
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Начальная дата в формате YYYY-MM-DD
        - name: end_time
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Конечная дата в формате YYYY-MM-DD
      responses:
        "200":
          description: Успешный ответ с динамикой создания кампаний
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CampaignDynamic"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalError"

  /reaction-time:
    get:
      summary: Получение времени реакции клиентов
      description: Возвращает статистику времени реакции клиентов для указанной кампании
      parameters:
        - name: campaign_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: ID кампании
      responses:
        "200":
          description: Успешный ответ со статистикой времени реакции
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReactionTimeMetrics"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /activity-time:
    get:
      summary: Получение статистики активности по времени
      description: Возвращает статистику активности пользователей по часам для указанной даты
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Дата в формате YYYY-MM-DD
      responses:
        "200":
          description: Успешный ответ со статистикой активности
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DailyTimeActivity"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalError"

  /predict-best-time:
    get:
      summary: Прогноз оптимального времени активности
      description: Возвращает прогноз наиболее эффективного времени для запуска кампаний
      responses:
        "200":
          description: Успешный ответ с прогнозом времени активности
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeActivityResponse"
        "500":
          $ref: "#/components/responses/InternalError"

  /regions-info:
    get:
      summary: Получение информации о регионах
      description: Возвращает статистическую информацию по всем регионам
      responses:
        "200":
          description: Успешный ответ с информацией о регионах
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegionsInfo"
        "500":
          $ref: "#/components/responses/InternalError"

components:
  schemas:
    Error:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
      required:
        - status
        - message

    ActivityMetrics:
      type: object
      properties:
        campaign_id:
          type: integer
          format: int64
        hourly_stats:
          type: array
          items:
            type: object
            properties:
              hour:
                type: string
                format: date-time
              clicks:
                type: integer

    CampaignStats:
      type: object
      properties:
        daily_stats:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
              clicks_count:
                type: integer
              percentage:
                type: number
                format: float
        monthly_stats:
          type: array
          items:
            type: object
            properties:
              month:
                type: string
                format: date
              clicks_count:
                type: integer
              percentage:
                type: number
                format: float
        total_clicks:
          type: integer

    CampaignDynamic:
      type: array
      items:
        type: object
        properties:
          date:
            type: string
            format: date
          count:
            type: integer
          campaigns:
            type: array
            items:
              $ref: "#/components/schemas/Campaign"

    Campaign:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        created_at:
          type: string
          format: date-time

    ReactionTimeMetrics:
      type: object
      properties:
        campaign_id:
          type: integer
          format: int64
        average_time:
          $ref: "#/components/schemas/FormattedDuration"
        median_time:
          $ref: "#/components/schemas/FormattedDuration"
        min_time:
          $ref: "#/components/schemas/FormattedDuration"
        max_time:
          $ref: "#/components/schemas/FormattedDuration"
        percentile_90th:
          $ref: "#/components/schemas/FormattedDuration"
        percentile_95th:
          $ref: "#/components/schemas/FormattedDuration"
        total_customers:
          type: integer

    FormattedDuration:
      type: object
      properties:
        years:
          type: integer
        months:
          type: integer
        days:
          type: integer
        hours:
          type: integer
        minutes:
          type: integer
        seconds:
          type: integer

    RegionHeatMap:
      type: array
      items:
        type: object
        properties:
          region_id:
            type: integer
          region_name:
            type: string
          activity_count:
            type: integer

    RegionClickStats:
      type: array
      items:
        type: object
        properties:
          region_id:
            type: integer
          click_count:
            type: integer

    DailyTimeActivity:
      type: object
      properties:
        date:
          type: string
          format: date
        day_of_week:
          type: string
        total_clicks:
          type: integer
        hour_stats:
          type: array
          items:
            type: object
            properties:
              hour:
                type: integer
                minimum: 0
                maximum: 23
              activity:
                type: integer

    TimeActivityResponse:
      type: object
      properties:
        day_stats:
          type: array
          items:
            type: object
            properties:
              day:
                type: string
              hour_stats:
                type: array
                items:
                  type: object
                  properties:
                    hour:
                      type: integer
                      minimum: 0
                      maximum: 23
                    activity:
                      type: integer

    CampaignList:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        per_page:
          type: integer
        campaigns:
          type: array
          items:
            $ref: "#/components/schemas/Campaign"

    RegionsInfo:
      type: array
      items:
        type: object
        properties:
          region_id:
            type: integer
          region_name:
            type: string
          statistics:
            type: object
            properties:
              total_campaigns:
                type: integer
              total_clicks:
                type: integer
              average_response_time:
                type: number
                format: float

  responses:
    BadRequest:
      description: Неверные параметры запроса
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NotFound:
      description: Ресурс не найден
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalError:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
